export const SELECT_HISTORY_TAG = 'SELECT_HISTORY_TAG';
export const ADD_HISTORY_TAG = 'ADD_HISTORY_TAG';

export const ADD_TODO_SYNC_REQUEST = 'ADD_TODO_SYNC_REQUEST';
export const ADD_TODO_SYNC_RESPONSE = 'ADD_TODO_SYNC_RESPONSE';
export const TOGGLE_TODO = 'TOGGLE_TODO';

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
